$Imagesoft="ImageJ"
$name="20110210_Si_24_100_09l_03"

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("^o")
Send($name & ".tif")
Sleep(100)
Send("!o")
Sleep(300)

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("{ALT}")
Sleep(100)
Send("{RIGHT 2}")
Send("{DOWN 5}")
Send("{RIGHT 1}")
Send("{ENTER 1}")
Sleep(1000)

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Sleep(300)
Send("^s")
Send("{ENTER 1}")
Sleep(300)

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("{ALT}")
Sleep(100)
Send("{RIGHT 3}")
Send("{DOWN 2}")
Send("{ENTER 1}")
Sleep(300)
Send("^+s")
Sleep(300)

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("{ALT}")
Sleep(300)
Send("{DOWN 9}")
Send("{RIGHT 1}")
Send("{ENTER 1}")
Sleep(300)
Send($name & "a" &".tif")
Sleep(300)
Send("{ENTER 1}")
Sleep(300)
Send("^w")
Sleep(300)

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("^s")
Send("{ENTER 1}")
Sleep(300)
Send("^w")

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("^w")

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("^o")
Send($name & ".tif (blue).tif")
Sleep(100)
Send("!o")
Sleep(300)

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("^o")
Send($name & ".tif (green).tif")
Sleep(100)
Send("!o")
Sleep(300)

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("{ALT}")
Sleep(300)
Send("{RIGHT 2}")
Send("{DOWN 5}")
Send("{RIGHT 1}")
Send("{DOWN 1}")
Send("{ENTER 1}")
Sleep(300)
Send("{ENTER 1}")

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("{ALT}")
Sleep(300)
Send("{RIGHT 2}")
Send("{DOWN 1}")
Send("{RIGHT 1}")
Send("{DOWN 4}")
Send("{ENTER 1}")
Sleep(300)

WinActivate($Imagesoft,"")
WinWaitActive($Imagesoft,"")
Send("{ALT}")
Sleep(300)
Send("{DOWN 9}")
Send("{RIGHT 1}")
Send("{ENTER 1}")
Sleep(300)
Send("03" & ".tif")
Sleep(300)
Send("{ENTER 1}")
Sleep(300)
Send("^w")
Sleep(300)
Send("^w")
Sleep(300)

